### ISSUE TITLE
html-webpack-harddisk-plugin may not be compatible with webpack v4

### ISSUE THREAD

**Issue by SunChaoran** [jantimon/html-webpack-harddisk-plugin#12]
After i upgraded webpack to v4, html-webpack-harddisk-plugin did not work anymore.

**my devDependencies:**

```
"devDependencies": {
        ...
        "html-webpack-harddisk-plugin": "^0.1.0",
        "html-webpack-plugin": "webpack-contrib/html-webpack-plugin",
        ...
        "webpack": "^4.0.1",
        "webpack-cli": "^2.0.9",
        "webpack-dev-server": "^3.0.0",
         ...
    },
```

**my webpack config**

```
...
new HtmlWebpackPlugin({
    filename: path.join(__dirname, '/dist/app.dev.html'),
    template: path.join(__dirname, 'src/App.dev.html'),
    inject: true,
    alwaysWriteToDisk: true,
    minify: {
        removeComments: false,
        collapseWhitespace: false,
    },
}),
new HtmlWebpackHarddiskPlugin(),
...
```

**error info:**

```
yarn run v1.2.1
$ NODE_ENV=development webpack-dev-server --compress --progress --public --config webpack.config.js --mode development
 10% building modules 1/1 modules 0 activeGenerating SSL Certificate               
(node:45602) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:45602) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead

Project is running at https://0.0.0.0:9393/
webpack output is served from /dist/
404s will fallback to /dist/app.dev.html                                                                                                                                                                                       95% emitting unnamed compat plugin/Users/sunchaoran/Projects/arthas/node_modules/html-webpack-harddisk-plugin/index.js:41
      callback(null);
      ^

TypeError: callback is not a function
    at /Users/sunchaoran/Projects/arthas/node_modules/html-webpack-harddisk-plugin/index.js:41:7
    at /Users/sunchaoran/Projects/arthas/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by anderschbe** [comment]
I can confirm this:

`    "html-webpack-harddisk-plugin": "0.1.0",
    "html-webpack-plugin": "3.0.6",
    "webpack": "4.1.1"
    "webpack-cli": "2.0.10",
    "webpack-dev-server": "3.1.0",`

`      new HtmlWebpackPlugin({
        template: 'index.ejs',
        filename: 'index.vm',
        alwaysWriteToDisk: true,
        minify: production ? {
          removeComments: true,
          collapseWhitespace: true,
          removeAttributeQuotes: false
        } : undefined,
        metadata: {
          // available in index.ejs //
          server, baseUrl
        },
        chunksSortMode: 'dependency'
      }),

      new HtmlWebpackHarddiskPlugin(),`

`      new HtmlWebpackPlugin({
        template: 'index.ejs',
        filename: 'index.vm',
        alwaysWriteToDisk: true,
        minify: production ? {
          removeComments: true,
          collapseWhitespace: true,
          removeAttributeQuotes: false
        } : undefined,
        metadata: {
          // available in index.ejs //
          server, baseUrl
        },
        chunksSortMode: 'dependency'
      }),

      new HtmlWebpackHarddiskPlugin(),`

Same error (index.js line 41:7 callback is not a function

**Comment by mshmyw** [comment]
Same error

**Comment by jantimon** [comment]
Please try 0.2.0
