### ISSUE TITLE
Doesn't seem to work with webpack-dev-server and FaviconsWebpackPlugin

### ISSUE THREAD

**Issue by thomasjm** [jantimon/html-webpack-harddisk-plugin#14]
I'm trying to use this package to ensure that `favicons-webpack-plugin` and `html-webpack-plugin` will do their thing and inject generated favicon information into my `index.htm` file, but it doesn't seem to work.

I'm on the latest `webpack` and `webpack-cli`, and I've tried `webpack-dev-server` with and without `--hot`.

What happens is on the *first* build of a new `webpack-dev-server` session, the favicons are generated, but on every subsequent build they are not. This is also the same behavior I get if I don't use `html-webpack-harddisk-plugin`.

Interestingly, this problem seems to only apply to favicons. I also use `html-webpack-plugin` to inject a CSS stylesheet, and that works fine on every build.

I'm not sure where in the process this is going wrong, please let me know if there's a better place to file this issue.

**Comment by thomasjm** [comment]
Actually never mind, after upgrading to `webpack-cli` `3.1.0` which was released literally yesterday, it seems to be working. Closing...

**Comment by thomasjm** [comment]
My mistake, it was only temporarily working because of favicon caching from a production build. This issue remains a problem.

**Comment by Uzwername** [comment]
Hello @thomasjm,

Have you figured out why this was happening?

I'm facing the same issue & there's no info at all regarding the topic. Please help me (& others who are looking for the answer) if you finally figured out what was the issue.

**Comment by thomasjm** [comment]
Hmm @Uzwername, I think I actually gave up on this since it doesn't affect production builds. I got used to having a blank favicon on my development tab haha.

**Comment by Uzwername** [comment]
@thomasjm well, it's also a way of dealing with this.

Thank you anyway! :)

**Comment by jantimon** [comment]
fixed with the following versions:

html-webpack-plugin 5.x
favicons-webpack-plugin 5.x
html-webpack-harddisk-plugin 2.x
