### ISSUE TITLE
Webpack watch mode 4.42.1, and html-webpack-plugin 4.0.4 with cache enabled results that templates get erased

### ISSUE THREAD

**Issue by Reeywhaar** [jantimon/html-webpack-harddisk-plugin#24]
Given:
osx 10.14.6
node: 13.6.0
webpack: 4.42.1
html-webpack-plugin: 4.0.4
html-webpack-harddisk-plugin: 1.0.1

When running webpack in watch mode and html-webpack-plugin configured by default results that templates get erased after some time. Problem can be solved by providing `cache: false` to html-webpack-plugin settings.

Also, webpack configured to use devMiddleware so actual javascript is not emitted.

Maybe I can provide some additional info? If so, I'll be glad.

Thank you!

**Comment by jantimon** [comment]
The actual code is here:

https://github.com/jantimon/html-webpack-harddisk-plugin/blob/af642bf19723b3f1b5c4668938e3836233d5720c/index.js#L44-L64

As you can see there is no delete code - are you using additional plugins which edit the disk content?

**Comment by Reeywhaar** [comment]
Ok, so problem is that I also use clean-webpack-plugin. Steps are goes like:

* initial compilation:
  *  clean-webpack-plugin clears build directory
  *  harddisk-plugin writes build/template.html, build/some_other_page.html
* second compilation (I actually change content in js)
  * harddisk-plugin either writes all, or template.html or some_other_page.html depending whether content changed (like if we injected js with different hash).
  * clean-webpack-plugin either removes all, template.html or some_other_page.html. I am not yet sure what is his strategy.
* third compilation (i don't change anything, and just hit cmd+s)
  * harddisk-plugin do not emit anything because of cache
  * clean-webpack-plugin removes all (at least it can, but no 100% guarantee)

Interesting how at initial compilation clean-webpack-plugin goes first and harddisk-plugin second, but consequent compilation order is swapped.

So, I'm sure it's not harddisk-plugin problem anymore but rather proper configuration of clean-webpack-plugin. What do you think? Should I close the issue?

**Comment by koen-dev** [comment]
@Reeywhaar This is exactly what I am running into right now! Can you please tell me if you figured out what the correct configuration is for `clean-webpack-plugin`? 🙏

**Comment by Reeywhaar** [comment]
@koen-dev what I use is:
```
new CleanWebpackPlugin({
    cleanStaleWebpackAssets: false,
})
```

`clean-webpack-plugin` is `3.0.0`

Hope it will help.

**Comment by koen-dev** [comment]
@Reeywhaar Thanks for the fast reply! 

I started playing with the configuration of `clean-webpack-plugin` too. I generate `.cshtml` outside of the `output.path` which is why `CleanWebpackPlugin` didn't delete them correctly. 

So for me the following config works:
```js
new CleanWebpackPlugin({
    dry: false,
    dangerouslyAllowCleanPatternsOutsideProject: true,
})
```

Thank you so much for this! You have no idea how long I have been looking for the reason why my `webpack-dev-server` was stuck. 🎉
