### ISSUE TITLE
This should be part of html-webpack-plugin

### ISSUE THREAD

**Issue by dlindenkreuz** [jantimon/html-webpack-harddisk-plugin#25]
Wouldn't it make sense to bake this functionality into the actual html-webpack-plugin and include `alwaysWriteToDisk` option?

It feels wrong to install and load a second plugin by the same author, just to get a file on disk that the first plugin provides anyway (under different circumstances).

For example, [webpack-manifest-plugin offers disk output as a core option](https://github.com/danethurber/webpack-manifest-plugin#optionswritetofileemit).

**Comment by jantimon** [comment]
As you can see the html-webpack-harddisk-plugin has only ~45.000 downloads so it is not used much.  
If we add all those edge case requirements to the main plugin it will be very hard to mainain.

Btw you can set the outputfile system for the webpack-dev-server or use the watch mode to write all files to disk.

Writing files to memory instead to the disk is a performance feature to speed up the compilation process.

**Comment by dlindenkreuz** [comment]
> Writing files to memory instead to the disk is a performance feature to speed up the compilation process.

Exactly, this is why I wouldn't want to turn on disk output for all webpack-dev-server files.

> If we add all those edge case requirements to the main plugin it will be very hard to mainain.

I feel you, but since you are the author of both the main and the harddisk plugin, you'd probably want to keep the two packages in sync anyway, right? 😛 

This is my current use case:
- webpack-dev-server creates a SPA bundle that needs to be loaded in a Laravel app
- public/index.html gets written to the SPA's dist folder as index.blade.php
- Laravel app serves the index.blade.php file

This wouldn't be possible without writing the file to disk first. Please reconsider this (regardless of download stats), as this setup is pretty trivial and enables some use cases for integrating SPA apps with certain server environments.

If it helps, I could put together a PR to add `alwaysWriteToDisk` functionality to html-webpack-plugin.

**Comment by jantimon** [comment]
What exactly is the problem of installing 2 plugins instead of one?

**Comment by dlindenkreuz** [comment]
`alwaysWriteToDisk` functionality is implicitly split over two entries in a webpack config. Only using the option in html-webpack-plugin without the second plugin doesn't work, and from reading a config file, it's not obvious that html-webpack-harddisk-plugin is required to give meaning to that option.

I'd like to remove complexity from my team's webpack configs (we have quite a few) and prevent future confusion and frustration about things like this. Because both packages are managed by the same author (and all of the above reasons), I think it would be great and pretty natural to have this as a core feature.

We're using [webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin) which allows emitting files during dev, and so it served as the inspiration for this request.
