### ISSUE TITLE
output path is wrong when using webpack-dev-server

### ISSUE THREAD

**Issue by bennettrogers** [jantimon/html-webpack-harddisk-plugin#3]
Just a heads up that due to what appears to be a [bug in webpack](https://github.com/webpack/webpack-dev-server/issues/337), the output path used by this plugin is incorrect when using the CLI for the webpack-dev-server. It doesn't seem to be fixed as of webpack v2.1.0-beta.21.

The gist is that when using the dev-server, webpack overwrites the output.path specified in the config and sets it to `"/"`. This means that this plugin tries to write its output html to a path based at the filesystem root (which will likely fail with a permission error).

This problem doesn't happen when using the webpack-dev-server via its API (rather than the CLI).

**Comment by anvk** [comment]
It would help so many people if this issue is resolved.

**Comment by jantimon** [comment]
@anvk feel free to open a pull request 👍

**Comment by CaptEmulation** [comment]
@anvk you can now pass in an `outputPath` option to the `HtmlWebpackHardiskPlugin` constructor to output to a specific location.  See #6.  Available with version 0.1.0 and above.
