### ISSUE TITLE
Warning in console when you last version of "html-webpack-plugin"

### ISSUE THREAD

**Issue by ArtemZag** [jantimon/html-webpack-harddisk-plugin#4]
I've updated html-webpack-plugin. Now I get warning on build:

"Using html-webpack-plugin-after-html-processing without returning a result is deprecated."

**Comment by jantimon** [comment]
Oh thanks will fix it soon 👍

**Comment by alfaslash** [comment]
I have the same problem after the upgrade `html-webpack-plugin`.
@jantimon  could you solve this problem?

**Comment by jantimon** [comment]
The deprecation note was introduced in html-webpack-plugin 2.24.0 and fixed in 2.24.1 see https://github.com/ampedandwired/html-webpack-plugin/pull/478
