### ISSUE TITLE
Documentation: one "true" too much? What about webpack 5?

### ISSUE THREAD

**Issue by rowild** [jantimon/html-webpack-harddisk-plugin#47]
Shouldn't `alwaysWriteToDisk` in the 2nd example (with `filename: "Demo.html`) also be set to `false`?

And is there a webpack 5 support coming up? Currently it does not work. Would be really awesome!

**Comment by jantimon** [comment]
Hmm why do you think it should rather be `false`?
Unfortunately right now I don't have much time to work on this project..

**Comment by rowild** [comment]
Because you mention 3 templates, but only the first should be set to `alwaysWriteToDisk: true`:

```js
plugins: [
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: true
	}),
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: true,    // <== shouldn't this one be set to false?
		filename: 'demo.html'
	}),
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: false,
		filename: 'test.html'
	}),
  new HtmlWebpackHarddiskPlugin()
]  
```

Or do I misunderstand you?

**Comment by rowild** [comment]
@janitom ?

**Comment by jantimon** [comment]
Why should only the first be written to disk?

**Comment by rowild** [comment]
@jantimon  Because the documentation says so ...???

`Even if you generate multiple files make sure that you add the HtmlWebpackHarddiskPlugin only once:`

Am I misunderstanding something here?

**Comment by jantimon** [comment]
Ah it means that instead of

```
plugins: [
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: true
	}),
  new HtmlWebpackHarddiskPlugin(),
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: true,  
		filename: 'demo.html'
	}),
  new HtmlWebpackHarddiskPlugin(),
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: false,
		filename: 'test.html'
	}),
  new HtmlWebpackHarddiskPlugin()
]  
```

your should only write

```
plugins: [
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: true
	}),
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: true, 
		filename: 'demo.html'
	}),
  new HtmlWebpackPlugin({
		alwaysWriteToDisk: false,
		filename: 'test.html'
	}),
  new HtmlWebpackHarddiskPlugin()
]  
```

**Comment by rowild** [comment]
Aaaah! ***ding*** (that#s the sound of the light being turned on)
Well, that I thoroughly misunderstood!! Thanks for turning on my lights!

I am closing this, but not without mentioning that it unfortunately does not help with Hot reloading, when working with (e.g. ejs) partials. Only when the file defined in the HtmlWebpackPlugin has changes and  is saved, then partials are picked up as well. 

I know you have no time, but in case you want to dig into it, I can prepare a demo on codesandbox.

**Comment by jantimon** [comment]
No worries - writing good docs is so hard... So I am very happy for any feedback :)

Your problem sounds like that the loader you are using is not supporting hot reloading.

**Comment by rowild** [comment]
You know: reading your docs now I wonder about myself why I so stubbornly and over so many days (weeks?) did not understand, what is written there. Your docs are actually totally clear! I wouldn't know how to write it differently... so: shame on me!

The situation with the reloading is very sad, though. I was hoping that your plugin would take care of the shortcoming of ejs loaders. But again I was wrong.

It a pity that this hot reloading problem is true for pug loaders, any and all ejs load plugins, mustache loaders, the standard lodash (which is a reduced ejs, if I am not mistaken)... I posted the problem everywhere, but nobody of any of those library maintainers seems to care.
The topic comes up quite often on stackoverflow, and google finds even more. And it was also true for webpack 4. I wonder if the developers every use their own product? it seems you neither use multiple (ejs) templates with partials? 

Well... sorry for whining... I am just so desperate, because my knowledge does not suffice to pinpoint the problem.. and I needed get rid of my frustration...

**Comment by jantimon** [comment]
Actually there are two different things - recompiling and hot reloading.

recompiling is triggered by webpack - and webpack tracks a dependency or module graph to know which files cause recompilations. if a loader allow to register additional files (like partials) it must either convert those requests into webpack require calls or needs to add the file as dependency (https://webpack.js.org/api/loaders/#thisadddependency)

the standard html-webpack-plugin lodash loader has no special build in partial support at all..
however you can just use the webpack require function instead e.g.:

```js
<%= require('./another-ejs-file.ejs')({ some: data }) %>
```

the html-webpack-plugin will only provide a fallback loader for the index file so make sure that you have a loader configured for `./another-ejs-file.ejs`..


html hot reloading is hardly possible as it is hard to find out which parts have been changed by javascript in the meantime.
so you will probably need to reload manually.
